### ISSUE TITLE
Open/close option for MST page

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#101]
we need to have an "open/close" button for the keyboard in MST.  In a perfect case, the MST browser window would open with the keyboard, but once the user logs in, then the keyboard would go away.

**Comment by jimmyism-1** [comment]
@saratheindustrious Need to get assets for the close and open.

**Comment by saratheindustrious** [comment]
@JimmyMooreTheIndustrious let me know if these work:
04_Deliver/_updates-0501/

I also posted two JPGs for reference on placement.

**Comment by AudreyTheIndustrious** [comment]
verified
