### ISSUE TITLE
Prepare for CR1 Review

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/ATT#45]
To show during creative review 1 (*stretch goals)

- [ ] Updated User flow for application
- [ ] Updated Discover section design*
- [ ] Existing DTV carousel design
- [ ] Existing DTV package grid
- [ ] NEW Wireless carousel design*
- [ ] NEW Wireless "package grid"*
- [ ] 3PL selection interface
- [ ] 3PL static "video" pieces*

**Comment by saratheindustrious** [comment]
@AndyTheIndustrious - this is an ugly version of what will be an updated user flow. Does this look correct to you? I'm leaving out the detail on the 3PL video selection, but please let me know if i'm missing anything otherwise.

<img width="1180" alt="screen shot 2018-03-06 at 2 10 54 pm" src="https://user-images.githubusercontent.com/36420298/37052957-e4504c9e-2148-11e8-894f-20c82ec3b1e0.png">

**Comment by AndyTheIndustrious** [comment]
So good.  Dawn is eager to see.

**Comment by AudreyTheIndustrious** [comment]
should we just rename this to CR 2 or copy to new item?
