### ISSUE TITLE
Send an Elo to Target and Evolve

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#46]
from Wed Mar 7 meeting, @AndyTheIndustrious committed to sending one. Using this to track the action item.

**Comment by AudreyTheIndustrious** [comment]
Anyway – I’m happy to send a device to Brian and team.
1.	It will have the current (old) application, but I can explain that to him.
2.	We will need to buy another one.  I don’t think you want me to take it from Walmart inventory.

Target Corporation
C/O Christopher Case
50 S. 10th St. Suite 400 
TP3-11320
Minneapolis, MN 55403-2054

Can you please ship the one monitor to the below address?  Can you also please provide the tracking number?

Ship to Address:
Evolve
Attn: Nino/Lance
1625 Norwood Ave
Itasca, IL 60143

**Comment by AndyTheIndustrious** [comment]
What is this?

Did this information get to Chris?

Thank you.

Andy

**Comment by AudreyTheIndustrious** [comment]
Not yet. I can send it now. What “old” application will be on the fixture? Will chris know what that is?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
Yes.  That is what I sent him via FTP as discussed on the call.

Chris needs the shipping information for both Target and Evolve.

Thank you.

**Comment by AudreyTheIndustrious** [comment]
Ok, good. Where is the shipping address for Evolve?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
You received it yesterday morning at 10:49.

**Comment by AndyTheIndustrious** [comment]
Hi.  What is this?

Andy

**Comment by AudreyTheIndustrious** [comment]
It was created to track the shipping of the elo devices. I’ve already sent that info to chris. You don’t have to do anything here…you already gave chris the old app for the target device.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com
