### ISSUE TITLE
v1.0.0.8 sizing issue with the promo

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#51]

**Comment by saratheindustrious** [comment]
Promo looks too big.
![now - slide2](https://user-images.githubusercontent.com/36420298/38470113-6250c856-3b2c-11e8-8caa-a06cf167dfdb.jpg)


![img_0180](https://user-images.githubusercontent.com/36420298/38470102-44aa6c76-3b2c-11e8-9ce4-dd12168558c5.jpg)

**Comment by jimmyism-1** [comment]
DONE
