### ISSUE TITLE
v1.0.0.8 update the nav bar to switch back-and-forth between DirecTV and wireless

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#52]

**Comment by saratheindustrious** [comment]
Please make sure you're using the latest versions of directv and directvnow nav bars - they should link to wireless at the bottom.

![img_0179](https://user-images.githubusercontent.com/36420298/38470099-33de9a0c-3b2c-11e8-93cd-af51bf4ea478.jpg)
![img_0180](https://user-images.githubusercontent.com/36420298/38470100-33ec4814-3b2c-11e8-9f6e-ca0da6aa533e.jpg)

**Comment by jimmyism-1** [comment]
DONE
