### ISSUE TITLE
v1.0.0.8 - update "4 line" plan images on wireless

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/ATT#60]
There was a typo in the old version that says "3 lines".
choice-4.png
![choice-4](https://user-images.githubusercontent.com/36420298/38470322-f5d86b36-3b2e-11e8-90df-fb974e07cea8.png)

plus-4.png
![plus-4](https://user-images.githubusercontent.com/36420298/38470323-f882815a-3b2e-11e8-828f-7d597aa88417.png)

New files posted to deliver and _updates-0408 folder.

**Comment by jimmyism-1** [comment]
DONE
