### ISSUE TITLE
v1.0.0.8 - directv now carousel, item 4; remove extra space at bottom of demos

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/ATT#61]
can you remove the extra space at the bottom of the demo videos on the 4th carousel item of directv now?

if you need me to give you a shorter background image, just let me know how long it should be.
![img_0182](https://user-images.githubusercontent.com/36420298/38470362-a55e2b5e-3b2f-11e8-8ec4-00be1301a28f.jpg)

**Comment by jimmyism-1** [comment]
DONE
