### ISSUE TITLE
New video for Attract Loop

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/ATT#62]
1. New video from the agency here:
 – Projects/ATT/LTB-Enhancements/Design/04_Deliver/Attract/20180410_Costco_(New_Network_Claim)_(1920x1080)_E.m
–https://www.dropbox.com/s/jn4ar12t6ujo74a/20180410_Costco_%28New_Network_Claim%29_%281920x1080%29_E.mp4?dl=0

2. The "New Network Claim" video cannot be played immediately before or after a Wireless message, so I've created a text document that lists the order.
– Projects/ATT/LTB-Enhancements/Design/04_Deliver/Attract/playlist.docx

3. I also broke out our attract elements into different videos, so those will need encoding as well.
– 18-0411-25000
– 18-0411-TVUnbound
– 18-04110TVGottaHaves-Premium

There will be a new gift card video when I get the details of the promotion.

**Comment by saratheindustrious** [comment]
Hold on item one above for new video asset from the agency.

**Comment by saratheindustrious** [comment]
@AndyTheIndustrious 
Updated video posted to 04_Deliver and updated in the playlist doc.
20180411_Walmart_(New_Network_Claim)_(1920x1080)_E.mp4

**Comment by AndyTheIndustrious** [comment]
This is complete.  Thank you.

**Comment by AndyTheIndustrious** [comment]
This is complete.

Andy Austin
President / The Industrious
mobile // +1.323.736.2121<tel:+1.323.736.2121>
mobile // +44.(0)7454.572.928


On Apr 23, 2018, at 10:15 PM, Audrey Sniezek <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #62<https://github.com/TheIndustrious/ATT/issues/62>.
