### ISSUE TITLE
Presentation "auto" start on the half hour

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#65]
How does the presentation start every 30 minutes?

**Comment by saratheindustrious** [comment]
I will provide a countdown clock video from Rob. I believe this is an @AndyTheIndustrious question.

![countdownblackbelow](https://user-images.githubusercontent.com/36420298/38672885-7e42c872-3e1d-11e8-8242-1081e57c0dd6.png)

**Comment by AndyTheIndustrious** [comment]
Excellent. Answer is yes.

Andy

Andy Austin
President / The Industrious
mobile // +1.323.736.2121<tel:+1.323.736.2121>
mobile // +44.(0)7454.572.928


On Apr 12, 2018, at 5:48 AM, saratheindustrious <notifications@github.com<mailto:notifications@github.com>> wrote:


I will provide a countdown clock video from Rob. I believe this is an @AndyTheIndustrious<https://github.com/AndyTheIndustrious> question.

[countdownblackbelow]<https://user-images.githubusercontent.com/36420298/38672885-7e42c872-3e1d-11e8-8242-1081e57c0dd6.png>

**Comment by AudreyTheIndustrious** [comment]
I understand something will be there, but how will it work? Each speaker will end at different times, roughly around the same time so will the countdown be static or dynamic? Will it auto play at the end of the presentation or need to be kicked off each time manually? Same for how it stops? Also, the presentation, will it automatically start/stop or will someone physically have to go to the podium and restart it?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
Good morning!

I’ll be standing there.  When the presenter is finished, she will leave the deck on the last slide.

I’ll jump up there and start the timer.

When the timer is complete, I’ll start the deck for the next presenter.

I don’t see why this won’t work?  I’m grateful for your taking a look at the details for sure.

Andy

**Comment by AudreyTheIndustrious** [comment]
Sounds like a fun job! Thanks for clarifying. I spoke with Cristina and she confirms another moderator will be there if you have to step away. If you are doing that, does that mean Chris is doing L-T-B or are you hopping between stations?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
Chris isn't doing anything except for tech support and he departs Wednesday afternoon.

If I need to step away from Disxocer L-T-B for three minutes, that's fine.

Thank you.

Andy

Andy Austin
President / The Industrious
mobile // +1.323.736.2121<tel:+1.323.736.2121>
mobile // +44.(0)7454.572.928


On Apr 12, 2018, at 2:11 PM, Audrey Sniezek <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds like a fun job! Thanks for clarifying. I spoke with Cristina and she confirms another moderator will be there if you have to step away. If you are doing that, does that mean Chris is doing L-T-B or are you hopping between stations?

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com<http://wearetheindustrious.com>

**Comment by AudreyTheIndustrious** [comment]
Got it, thank you.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by saratheindustrious** [comment]
Video is here:
[04_Deliver/Countdown/Countdown FULL v01.mov](https://www.dropbox.com/s/w7yj49ask25nn4m/Countdown%20FULL%20v01.mov?dl=0)

**Comment by AndyTheIndustrious** [comment]
AWESOME.

I should have showed this on the executive call today.

**Comment by AudreyTheIndustrious** [comment]
How do you want to handle the timer if the speaker runs longer than 15 minutes?

If we stop the timer early to start on the half hour, people tracking the timer will be late to the next presentation. And, given the overhead of launching the presentation each time, it’s never going to end on time.


Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com

**Comment by AndyTheIndustrious** [comment]
If the speaker goes long, then I’m going to scrub to the right spot in the video to allow the video to end right on time.

Right?

Andy

**Comment by AudreyTheIndustrious** [comment]
Excellent.

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com
