### ISSUE TITLE
How does the timer start?

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#66]
Every presenter will have their own rhythm and temp. How does the timer start when the presentation is complete and how does it end when the next shift/speaker is up to present?

**Comment by saratheindustrious** [comment]
Last I checked, @AndyTheIndustrious  is planning on managing this manually. Again, going to let him answer that.

**Comment by AndyTheIndustrious** [comment]
Correct.

I'll run the timer video at the end of a presentation and run the deck when the timer ends.

If a previous presentation goes long, I'll scrub to the right point on the timer.

Andy

Andy Austin
President / The Industrious
mobile // +1.323.736.2121<tel:+1.323.736.2121>
mobile // +44.(0)7454.572.928


On Apr 12, 2018, at 5:49 AM, saratheindustrious <notifications@github.com<mailto:notifications@github.com>> wrote:


Last I checked, @AndyTheIndustrious<https://github.com/AndyTheIndustrious> is planning on managing this manually. Again, going to let him answer that.
