### ISSUE TITLE
MST03 COMP

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#68]
:09 The text "Allows sales reps to personalize recommendations is shown for too short of time it literally "flies by". I have no time to read it. 

1:45 feels too short. I just have time to read the sentence and then the images are gone. I have no time to absorb what is shown as well as read the text. it needs just a second or two more here.

**Comment by saratheindustrious** [comment]
Agree. I posted some feedback in frame.io to reduce the text and lengthen the time it's on screen. I think that's a better solution than updating the footage at this point. 

If we do have to add more footage in, we can do so over the weekend but it will be significant effort.

**Comment by saratheindustrious** [comment]
Fixed in footage delivered to Rob Friday evening. _MST03-footage-1, MST03-footage-2_
