### ISSUE TITLE
OPUS1

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#70]
0:00:30 Wow! those teeth! :) 

Not sure if there is anything you can do about this, but there is nothing really to focus on during this section. The tablet is partially out of frame and even though the woman is directing our attention to it, it's the teeth that stand out because they have the most motion in that frame. I laughed when I watched that segment. Is that Mark?

**Comment by saratheindustrious** [comment]
That's Cary. We had picture-lock approval as of yesterday so it would take quite a bit of effort to change, re-compile and re-render at this point. I'll suggest it to Casey if there are other changes that require a re-render.
