### ISSUE TITLE
DTV NOW Try videos are missing from V13

### ISSUE THREAD

**Issue by AndyTheIndustrious** [TheIndustrious/ATT#74]
The LTB Try videos are missing from the V10 ZIP file.  So that section of the application doesn't work.  Luckily, everything works fine as long as the videos are copied into the ..Assets\Video folder.  

Please make sure we check this as each machine is installed. 

Thank you.

**Comment by AudreyTheIndustrious** [comment]
are these still missing? I can't tell from the current video list in the build if they are considered there or not.

**Comment by AndyTheIndustrious** [comment]
SHIT.

They are missing.

Nice catch.

Demo1.wmv, demo2.wmv, demo3.wmv and demo4.wmv need to be put in the assets\videos folder.

We need to get this into the Rosie Azure instance please.

Andy

**Comment by jimmyism-1** [comment]
Added back to the build  DONE

**Comment by AudreyTheIndustrious** [comment]
Are you posting the updated build only to the cloud? Can we also have it posted in the development folder? Or point me to where I can find the build? I don’t see a build with all of the git changes from today.

Thank  you!

Audrey Sniezek
Project Manager / The Industrious
mobile // +1.425.233.4407
web // wearetheindustrious.com
