### ISSUE TITLE
Walmart specific attract loop

### ISSUE THREAD

**Issue by AndyTheIndustrious** [TheIndustrious/ATT#75]
We are supposed to be receiving a Walmart specific attract loop with the new Walmart gift card value.  That needs to be sent out to each machine when it comes online.

**Comment by saratheindustrious** [comment]
This is posted in deliver but is not in build 12.
Projects/ATT/LTB-Enhancements/Design/04_Deliver/Attract/Attract WM 041918.mov

**Comment by AndyTheIndustrious** [comment]
Luckily – it is in the distribution package.  It just isn’t in the playlist.

Building the playlist now and will forward to Sara for her to review on her machine.  She will only need to replace one text file.

Please stand by.

Andy

**Comment by AndyTheIndustrious** [comment]
This is fixed with the new DataStore.xml.

Let’s make sure that the new DataStore.xml is part of the Rosie distribution package please.

Thank you.

Andy
