### ISSUE TITLE
replace Best Buy assets on Walmart kiosks

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#76]
"PROMOTION_NOW_SIDE_IMAGE": "pack://siteoforigin:,,,/Assets/Images/Promos/promo-giftcard-bestbuy150.png",
    "PROMOTION_PREMIUM_SIDE_IMAGE": "pack://siteoforigin:,,,/Assets/Images/Promos/promo-giftcard-bestbuy150.png",
    "PROMOTION_WIRELESS_SIDE_IMAGE": "pack://siteoforigin:,,,/Assets/Images/Promos/promo-giftcard-bestbuy150.png",

    "PROMOTION_NOW_FEATURE_IMAGE": "pack://siteoforigin:,,,/Assets/Images/Learn/Now/content-now-promo.jpg",
    "PROMOTION_PREMIUM_FEATURE_IMAGE": "pack://siteoforigin:,,,/Assets/Images/Learn/Premium/content-premium-promo.jpg",

    "PROMOTION_PREMIUM_PACKAGE_IMAGE": "pack://siteoforigin:,,,/Assets/Images/Promos/promo-packages-bestbuy.png",
    "PROMOTION_NOW_PACKAGE_IMAGE": "pack://siteoforigin:,,,/Assets/Images/Promos/promo-packages-bestbuy.png",
    "PROMOTION_WIRELESS_PACKAGE_IMAGE": "pack://siteoforigin:,,,/Assets/Images/Promos/promo-packages-bestbuy.png",

**Comment by AndyTheIndustrious** [comment]
The config file is completed.  I think we can close this ticket.

Thank you.

Andy
