### ISSUE TITLE
DIRECTV Page 02 rendering incorrect - Build 13

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#83]
Screen rendering appears off.

Select I have DIRECTV, then tap NEXT
Tap 01
Confirm GOT page appears
Tap NEXT

Expected: 02 screen appears and content appears in the right place

Observed: 
1) the start menu screen appears and the 02 screen is cropped at the bottom. 

2) page 02 has overlapping content (presumably this content belongs lower on the page) see screen capture.

Sara's assets look right. https://www.dropbox.com/sh/j1otjd4of7ji5pi/AADBBCgHVNteJ-5GRJWMw2Yba?dl=0

![image](https://user-images.githubusercontent.com/36212831/39165808-20324240-473b-11e8-98aa-559531b6601f.png)

![image](https://user-images.githubusercontent.com/36212831/39165827-349fd490-473b-11e8-8c60-e945c6690335.png)

**Comment by jimmyism-1** [comment]
DONE
