### ISSUE TITLE
Page times out too quickly

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#86]
Steps: 
Tap "I don't have either of these yet"

Observed:
Find out which DIRECTV product is right for you blips past before I can absorb the content presented. 

Expected:
User should have a moment to view what is being displayed before automatically being taken to the next page (How do you watch?).  Perhaps we don't automatically enable the "let's go" button and let users tap that or anywhere on the screen to continue when they are ready?

**Comment by jimmyism-1** [comment]
BY DESIGN, there is a setting in the config (PRE_TIMEOUT) that sets the timeout.
