### ISSUE TITLE
Discover Q3 button selection doesn't fill entire button area

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#87]
When user is asked to select the "must haves" (Discover Q3) and a button is selected here, the fill does not fill the entire button outline and the button outline is cut off at the bottom.

![image](https://user-images.githubusercontent.com/36212831/39166586-40a6a1d4-473f-11e8-9e8f-e8346a288e50.png)

**Comment by jimmyism-1** [comment]
DONE
