### ISSUE TITLE
Discover Q2, Slider is cropped on the bottom

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#88]
How many screens are on at once?
slider is cropped on bottom as in this image
![image](https://user-images.githubusercontent.com/36212831/39166838-aeb6c6da-4740-11e8-9d79-46d41a7ff2db.png)

Should be:
![image](https://user-images.githubusercontent.com/36212831/39166802-82ff2618-4740-11e8-8a82-d28cf64b6044.png)

**Comment by jimmyism-1** [comment]
DONE
