### ISSUE TITLE
Call me/message me still observed in the app

### ISSUE THREAD

**Issue by AudreyTheIndustrious** [TheIndustrious/ATT#89]
Switch from Cable
Get the best with DIRECTV

Tap the page and another page with Call me Message me content appears. I thought we pulled this for this release.

![image](https://user-images.githubusercontent.com/36212831/39167027-b10b864a-4741-11e8-8fc4-d85d57b73c60.png)

![image](https://user-images.githubusercontent.com/36212831/39166974-5fd4ce8a-4741-11e8-95a3-0614d35e41e1.png)

**Comment by jimmyism-1** [comment]
DONE
