### ISSUE TITLE
LTB - 3PL Next - Add General Service Terms

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/ATT#94]
Add these general service terms to Next page:

GEN. WIRELESS: Subj. to Wireless Customer Agmt at att.com/wca. Svc not for resale. Deposit: Service deposit may apply. Limits: Purchase & line limits apply. Credit approval, activation (up to $45/line) and other fees, monthly & other charges per line apply. See plan details & att.com/additional charges for more details. Coverage & svc not avail. everywhere. You get an off-net (roaming) usage allowance for each svc. If you exceed the allowance, your svc(s) may be restricted or terminated. International and domestic off-net data may be at 2G speeds. Other restr’s apply & may result in svc termination. AT&T svc is subject to AT&T network management policies, see att.com/broadbandinfo for details. Offers, pricing, terms & restrictions subject to change and may be discontinued at any time without notice.

(via email from Cristina 4/25)

**Comment by saratheindustrious** [comment]
@JimmyMooreTheIndustrious Two new images for 3PL are posted to deliver:

04_Deliver/_updates-0426/3PL

- hbo4life.jpg
- next.jpg (note - this page is now longer than it previously was)

**Comment by AudreyTheIndustrious** [comment]
next.jpg is there in build 15
