### ISSUE TITLE
LTB - Attract Loop sequence updates

### ISSUE THREAD

**Issue by saratheindustrious** [TheIndustrious/ATT#96]
We have new creative from Alissa:

This is her playlist:
- Westworld Montage
- DTV Thumbs Up
- Samsung Galaxy S9 (this should already be running) _(don't think I have this)_
- Bundle
- Westworld Montage
- Unlimited with HBO
- New Network Claim (this should already be running)
- DTV NOW Hands On
- iPhone X – LA offer (this should already be running) _(not using this)_
- Buh-Bye Cable – NY Offer (this should already be running)  _(not using this)_

I need to watch each piece and see if we are replicating elements from these new videos and create a cohesive playlist.

**Comment by saratheindustrious** [comment]
@JimmyMooreTheIndustrious - New video assets to be encoded as WMV are here:
ATT/LTB-Enhancements/Design/01_Assets/18-0426-fromAlissa/NRO Digital Files for Q2

- Note that 3 of them were provided as 4k (but don't need to be)
- If you can post them to Deliver/Attract for Andy, that would be great

@AndyTheIndustrious - The playlist.docx in deliver has been updated. I've tried to merge Alissa's playlist with our elements to have a CTA up frequently. It's not ideal but unless we want to create some new content this is the best I can do with what I have.

All, I've placed all out-of-date files into an _archive folder within Deliver/Attract to clear up the folder, in case we need to bring them back.

**Comment by AndyTheIndustrious** [comment]
This looks great.  Thank you.

When Jimmy does the encoding, I can work the PLL.

Jimmy – I presume the new assets will go in a Rosie update tonight or tomorrow night or maybe over the weekend?

Andy

**Comment by saratheindustrious** [comment]
@AndyTheIndustrious 

- New assets and playlist here in **04_Deliver/Attract**
- Some of them still need to be converted to .wmv
- Note that 3 of them were provided as 4k (but don't need to be)

1.	GIFT CARD VIDEO - Attract WM 041918.mov (Walmart)
2.	20180416_Solution_Center_WESTWORLD_MONTAGE
3.	Attract DTV CTA 051118
4.	180420_Thumbs_Up_Emoji
5.	18-04110TVGottaHaves-Premium 
6.	20180411_Costco_(Galaxy_S9)_(1920x1080)_E
7.	GIFT CARD VIDEO - Attract WM 041918.mov (Walmart) * REPEAT
8.	180420_Bundle_Out_Money_Emoji
9.	Attract DTV CTA 051118
10.	20180416_Solution_Center_WESTWORLD_MONTAGE * REPEAT
11.	Attract DTV CTA 051118 
12.	180420_HBO_Dragon_Robot_Emoji
13.	20180411_Walmart_(New_Network_Claim)_(1920x1080)_E
14.	20180423_COSTCO_HANDS_ON_HD

**Comment by AudreyTheIndustrious** [comment]
done
